# Generated by Django 3.0.5 on 2020-06-05 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, default='2020-04-30')),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('cemail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('cimage', models.ImageField(blank=True, upload_to='CustomerImage')),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShopKeeper',
            fields=[
                ('shopname', models.CharField(max_length=100, unique=True)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, default='2020-04-30')),
                ('address', models.CharField(default='', max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('pincode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('semail', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('simage', models.ImageField(blank=True, upload_to='ShopKeeperImage/')),
                ('status', models.CharField(blank=True, default='A', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('cemail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Customer')),
                ('semail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app1.ShopKeeper')),
            ],
        ),
    ]
